services:
  db:
    image: postgres:15
    container_name: timetable_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    # This is the key change: pull the pre-built image from GHCR
    image: ghcr.io/YOUR_USERNAME/YOUR_REPOSITORY_NAME:latest
    container_name: timetable_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    # No build context or volumes needed for code, it's all in the image
    command: ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

volumes:
  db_data:
